# Generated by Django 4.2 on 2024-09-18 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0004_alter_produccion_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.produccion')),
            ],
        ),
    ]
