# Generated by Django 4.2 on 2024-09-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='id_producto',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='Nombre',
            new_name='id_product',
        ),
    ]
