# Generated by Django 4.2 on 2024-09-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_ubicacion_inv_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='descripcion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
