# Generated by Django 5.1 on 2024-09-19 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0005_inventario_descripcion'),
        ('logistica', '0004_details_pedidos_id_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_venta', models.DateTimeField()),
                ('total_venta', models.PositiveIntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.client')),
            ],
        ),
        migrations.CreateModel(
            name='detalles_venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio', models.PositiveIntegerField(max_length=3000)),
                ('descripcion', models.CharField(max_length=100)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
        ),
    ]
