# Generated by Django 4.2 on 2024-09-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talla',
            name='tipo',
            field=models.CharField(choices=[('numerico', 'numerico'), ('letreado', 'letreado')], max_length=50),
        ),
    ]
