# Generated by Django 4.2 on 2024-09-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_alter_talla_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='genero',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
