# Generated by Django 4.2 on 2024-09-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_produccion_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='genero',
            field=models.CharField(choices=[('hombre', 'hombre'), ('mujer', 'mujer'), ('niño', 'niño'), ('niña', 'niña')], max_length=30),
        ),
    ]
