# Generated by Django 4.2 on 2024-09-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_alter_produccion_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='id_producto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
