# Generated by Django 4.2 on 2024-09-18 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_client_pedidos_details_pedidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logistic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Descipcion', models.CharField(max_length=100)),
                ('fecha_envio', models.DateTimeField()),
                ('fecha_entrega', models.DateTimeField(blank=True)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.estate_log')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.pedidos')),
            ],
        ),
    ]
