# Generated by Django 4.2 on 2024-09-18 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_logistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='details_pedidos',
            name='id_pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logistica.pedidos'),
            preserve_default=False,
        ),
    ]
